<?php
/**
 * Class will be used for exceptions that are generated by class.json.php
 * getCode() method will return actual JSON error constant.
 */
class JSONException extends ZarafaException
{
}
?>